### ISSUE TITLE
Crash if ttlSeconds is undefined

### ISSUE THREAD

**Issue by anguslees** [awslabs/karpenter#475]
Derefs `*provisioner.Spec.TTLSeconds` without a nil check:
https://github.com/awslabs/karpenter/blob/26ef687fff31cf0a45b97b1758ca55df7641051e/pkg/controllers/provisioning/v1alpha1/reallocation/utilization.go#L84

<details>
<summary>Example crash:</summary>

```
2021-06-24T01:08:46.731Z        INFO    controller-runtime.metrics      metrics server is starting to listen    {"addr": ":8080"}
I0624 01:08:47.476586       1 leaderelection.go:243] attempting to acquire leader lease  karpenter/karpenter-leader-election...
2021-06-24T01:08:47.476Z        INFO    controller-runtime.manager      starting metrics server {"path": "/metrics"}
I0624 01:09:04.250662       1 leaderelection.go:253] successfully acquired lease karpenter/karpenter-leader-election
2021-06-24T01:09:04.250Z        INFO    controller.terminator   Starting EventSource    {"reconcilerGroup": "", "reconcilerKind": "Node", "source": "kind source: /, Kind="}
2021-06-24T01:09:04.251Z        INFO    controller.provisioner/allocator        Starting EventSource    {"reconcilerGroup": "provisioning.karpenter.sh", "reconcilerKind": "Provisioner", "source": "kind source: /, Kind="}
2021-06-24T01:09:04.252Z        INFO    controller.provisioner/reallocator      Starting EventSource    {"reconcilerGroup": "provisioning.karpenter.sh", "reconcilerKind": "Provisioner", "source": "kind source: /, Kind="}
2021-06-24T01:09:04.351Z        INFO    controller.terminator   Starting EventSource    {"reconcilerGroup": "", "reconcilerKind": "Node", "source": "kind source: /, Kind="}
2021-06-24T01:09:04.351Z        INFO    controller.terminator   Starting Controller     {"reconcilerGroup": "", "reconcilerKind": "Node"}
2021-06-24T01:09:04.351Z        INFO    controller.terminator   Starting workers        {"reconcilerGroup": "", "reconcilerKind": "Node", "worker count": 1}
2021-06-24T01:09:04.352Z        INFO    controller.provisioner/allocator        Starting EventSource    {"reconcilerGroup": "provisioning.karpenter.sh", "reconcilerKind": "Provisioner", "source": "kind source: /, Kind="}
2021-06-24T01:09:04.352Z        INFO    controller.provisioner/allocator        Starting Controller     {"reconcilerGroup": "provisioning.karpenter.sh", "reconcilerKind": "Provisioner"}
2021-06-24T01:09:04.352Z        INFO    controller.provisioner/allocator        Starting workers        {"reconcilerGroup": "provisioning.karpenter.sh", "reconcilerKind": "Provisioner", "worker count": 1}
2021-06-24T01:09:04.352Z        INFO    controller.provisioner/reallocator      Starting EventSource    {"reconcilerGroup": "provisioning.karpenter.sh", "reconcilerKind": "Provisioner", "source": "kind source: /, Kind="}
2021-06-24T01:09:04.352Z        INFO    controller.provisioner/reallocator      Starting Controller     {"reconcilerGroup": "provisioning.karpenter.sh", "reconcilerKind": "Provisioner"}
2021-06-24T01:09:04.352Z        INFO    controller.provisioner/reallocator      Starting workers        {"reconcilerGroup": "provisioning.karpenter.sh", "reconcilerKind": "Provisioner", "worker count": 1}
E0624 01:09:04.352745       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 313 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1d1d5e0, 0x30ea700)
        k8s.io/apimachinery@v0.19.7/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.19.7/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1d1d5e0, 0x30ea700)
        runtime/panic.go:969 +0x1b9
github.com/awslabs/karpenter/pkg/controllers/provisioning/v1alpha1/reallocation.(*Utilization).markUnderutilized(0xc0007fe4c0, 0x23354c0, 0xc000a94150, 0xc000713500, 0xc0008dc130, 0x1)
        github.com/awslabs/karpenter/pkg/controllers/provisioning/v1alpha1/reallocation/utilization.go:84 +0x688
github.com/awslabs/karpenter/pkg/controllers/provisioning/v1alpha1/reallocation.(*Controller).Reconcile(0xc00165d8c0, 0x23354c0, 0xc000a94150, 0x235e640, 0xc000713500, 0x200c786, 0x5, 0xc0008dc130, 0x1)
        github.com/awslabs/karpenter/pkg/controllers/provisioning/v1alpha1/reallocation/controller.go:72 +0x65
github.com/awslabs/karpenter/pkg/controllers.(*GenericController).Reconcile(0xc00165db20, 0x23354c0, 0xc000a94150, 0xc001b09730, 0x7, 0xc001b09720, 0x7, 0xc000a94150, 0x7f2ee7ebcb60, 0xc000491800, ...)
        github.com/awslabs/karpenter/pkg/controllers/controller.go:58 +0x22b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0009621e0, 0x2335400, 0xc001666480, 0x1dc0420, 0xc0012649e0)
        sigs.k8s.io/controller-runtime@v0.7.0-alpha.3/pkg/internal/controller/controller.go:263 +0x2f5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0009621e0, 0x2335400, 0xc001666480, 0xc00012c000)
        sigs.k8s.io/controller-runtime@v0.7.0-alpha.3/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x2335400, 0xc001666480)
        sigs.k8s.io/controller-runtime@v0.7.0-alpha.3/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0002c8f50)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001903f50, 0x22f4900, 0xc000a94090, 0xc001666401, 0xc00012c000)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002c8f50, 0x3b9aca00, 0x0, 0x1, 0xc00012c000)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x2335400, 0xc001666480, 0xc00065bfe0, 0x3b9aca00, 0x0, 0x1)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x2335400, 0xc001666480, 0xc00065bfe0, 0x3b9aca00)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        sigs.k8s.io/controller-runtime@v0.7.0-alpha.3/pkg/internal/controller/controller.go:195 +0x4e7
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a7c9e8]

goroutine 313 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        k8s.io/apimachinery@v0.19.7/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x1d1d5e0, 0x30ea700)
        runtime/panic.go:969 +0x1b9
github.com/awslabs/karpenter/pkg/controllers/provisioning/v1alpha1/reallocation.(*Utilization).markUnderutilized(0xc0007fe4c0, 0x23354c0, 0xc000a94150, 0xc000713500, 0xc0008dc130, 0x1)
        github.com/awslabs/karpenter/pkg/controllers/provisioning/v1alpha1/reallocation/utilization.go:84 +0x688
github.com/awslabs/karpenter/pkg/controllers/provisioning/v1alpha1/reallocation.(*Controller).Reconcile(0xc00165d8c0, 0x23354c0, 0xc000a94150, 0x235e640, 0xc000713500, 0x200c786, 0x5, 0xc0008dc130, 0x1)
        github.com/awslabs/karpenter/pkg/controllers/provisioning/v1alpha1/reallocation/controller.go:72 +0x65
github.com/awslabs/karpenter/pkg/controllers.(*GenericController).Reconcile(0xc00165db20, 0x23354c0, 0xc000a94150, 0xc001b09730, 0x7, 0xc001b09720, 0x7, 0xc000a94150, 0x7f2ee7ebcb60, 0xc000491800, ...)
        github.com/awslabs/karpenter/pkg/controllers/controller.go:58 +0x22b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0009621e0, 0x2335400, 0xc001666480, 0x1dc0420, 0xc0012649e0)
        sigs.k8s.io/controller-runtime@v0.7.0-alpha.3/pkg/internal/controller/controller.go:263 +0x2f5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0009621e0, 0x2335400, 0xc001666480, 0xc00012c000)
        sigs.k8s.io/controller-runtime@v0.7.0-alpha.3/pkg/internal/controller/controller.go:235 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x2335400, 0xc001666480)
        sigs.k8s.io/controller-runtime@v0.7.0-alpha.3/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0002c8f50)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001903f50, 0x22f4900, 0xc000a94090, 0xc001666401, 0xc00012c000)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002c8f50, 0x3b9aca00, 0x0, 0x1, 0xc00012c000)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x2335400, 0xc001666480, 0xc00065bfe0, 0x3b9aca00, 0x0, 0x1)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x2335400, 0xc001666480, 0xc00065bfe0, 0x3b9aca00)
        k8s.io/apimachinery@v0.19.7/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        sigs.k8s.io/controller-runtime@v0.7.0-alpha.3/pkg/internal/controller/controller.go:195 +0x4e7
```

</details>

**Comment by ellistarn** [comment]
Thanks for the report. This was fixed in https://github.com/awslabs/karpenter/pull/464 and will be released in v0.2.7.
