### ISSUE TITLE
Panic when Karpenter starts

### ISSUE THREAD

**Issue by allamand** [awslabs/karpenter#818]
## Version

**Karpenter**: v0.4.3

**Kubernetes**: v1.21

## Actual Behavior

Panic in the log when the pod Startup

```
k logs -n kube-system karpenter-controller-6f4d674488-bj87j
2021-11-19T18:22:55.757Z	INFO	Successfully created the logger.
2021-11-19T18:22:55.757Z	INFO	Logging level set to: info
{"level":"info","ts":1637346175.861402,"logger":"fallback","caller":"injection/injection.go:61","msg":"Starting informers..."}
I1119 18:22:55.910033       1 leaderelection.go:243] attempting to acquire leader lease kube-system/karpenter-leader-election...
2021-11-19T18:22:55.910Z	INFO	controller	starting metrics server	{"commit": "dc47849", "path": "/metrics"}
2021-11-19T18:23:13.046Z	INFO	controller.controller.Metrics	Starting EventSource	{"commit": "dc47849", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "source": "kind source: /, Kind="}
2021-11-19T18:23:13.046Z	INFO	controller.controller.Allocation	Starting EventSource	{"commit": "dc47849", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "source": "kind source: /, Kind="}
2021-11-19T18:23:13.047Z	INFO	controller.controller.Termination	Starting EventSource	{"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node", "source": "kind source: /, Kind="}
2021-11-19T18:23:13.047Z	INFO	controller.controller.Node	Starting EventSource	{"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node", "source": "kind source: /, Kind="}
I1119 18:23:13.046364       1 leaderelection.go:253] successfully acquired lease kube-system/karpenter-leader-election
2021-11-19T18:23:13.147Z	INFO	controller.controller.Node	Starting EventSource	{"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node", "source": "kind source: /, Kind="}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Node	Starting EventSource	{"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node", "source": "kind source: /, Kind="}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Node	Starting Controller	{"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node"}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Node	Starting workers	{"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node", "worker count": 10}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Metrics	Starting Controller	{"commit": "dc47849", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner"}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Metrics	Starting workers	{"commit": "dc47849", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "worker count": 10}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Allocation	Starting EventSource	{"commit": "dc47849", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "source": "kind source: /, Kind="}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Allocation	Starting Controller	{"commit": "dc47849", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner"}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Allocation	Starting workers	{"commit": "dc47849", "reconciler group": "karpenter.sh", "reconciler kind": "Provisioner", "worker count": 10}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Termination	Starting Controller	{"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node"}
2021-11-19T18:23:13.147Z	INFO	controller.controller.Termination	Starting workers	{"commit": "dc47849", "reconciler group": "", "reconciler kind": "Node", "worker count": 10}
E1119 18:23:13.148450       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 439 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1dc5800, 0x37a1200})
	k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:74 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1dc5800, 0x37a1200})
	runtime/panic.go:1038 +0x215
github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1.Deserialize(0xc000256798)
	github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1/provider.go:55 +0x96
github.com/awslabs/karpenter/pkg/cloudprovider/aws.(*CloudProvider).GetInstanceTypes(0xc0007f5060, {0x250b3d8, 0xc0009774a0}, 0x0)
	github.com/awslabs/karpenter/pkg/cloudprovider/aws/cloudprovider.go:136 +0x2f
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateNodeCounts(0xc0004c1be0, {0x250b3d8, 0xc0009774a0}, 0xc000256680)
	github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:101 +0x65
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateCounts.func1(0x0)
	github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:94 +0x57
k8s.io/client-go/util/workqueue.ParallelizeUntil.func1()
	k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:90 +0x150
created by k8s.io/client-go/util/workqueue.ParallelizeUntil
	k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:76 +0x1dc
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16d1f76]

goroutine 439 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	k8s.io/apimachinery@v0.20.7/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1dc5800, 0x37a1200})
	runtime/panic.go:1038 +0x215
github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1.Deserialize(0xc000256798)
	github.com/awslabs/karpenter/pkg/cloudprovider/aws/apis/v1alpha1/provider.go:55 +0x96
github.com/awslabs/karpenter/pkg/cloudprovider/aws.(*CloudProvider).GetInstanceTypes(0xc0007f5060, {0x250b3d8, 0xc0009774a0}, 0x0)
	github.com/awslabs/karpenter/pkg/cloudprovider/aws/cloudprovider.go:136 +0x2f
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateNodeCounts(0xc0004c1be0, {0x250b3d8, 0xc0009774a0}, 0xc000256680)
	github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:101 +0x65
github.com/awslabs/karpenter/pkg/controllers/metrics.(*Controller).updateCounts.func1(0x0)
	github.com/awslabs/karpenter/pkg/controllers/metrics/controller.go:94 +0x57
k8s.io/client-go/util/workqueue.ParallelizeUntil.func1()
	k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:90 +0x150
created by k8s.io/client-go/util/workqueue.ParallelizeUntil
	k8s.io/client-go@v0.20.7/util/workqueue/parallelizer.go:76 +0x1dc
```

This may be related to some missconfigured IRSA rights, but it should not panic

**Comment by ellistarn** [comment]
It looks like you created a provisioner before the validator/defaulter was installed. This is a known issue and fixed in the next release. This can happen if you're exceptionally fast about deploying the default provisioner before the install is complete (through automation or otherwise). 

Still -- we shouldn't be panicing. I'll have a PR out ASAP.
